language: csharp

addons:
  apt:
    packages:
       - msbuild

sudo: false # use the new container-based Travis infrastructure
dist: trusty # Ubuntu 14.04
mono: latest
dotnet: 2.1.2

script:
  - dotnet --info
  - ./build.sh Default